apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport
spec:
  type: NodePort
  selector:
    app: dynamic-deployment-zigsce  # This should match the labels of your pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # NodePort: 30007 (Optional: Kubernetes chooses a port if not specified, in the range 30000-32767)
